### ISSUE TITLE
sqlite3错误

### ISSUE THREAD

**Issue by comradeXiong** [ZegWe/Dota2Bot#2]
Traceback (most recent call last):
  File "app.py", line 51, in <module>
    init()
  File "app.py", line 47, in init
    managers[group].add_plugin('DOTA2战绩播报', True)
  File "/root/dota2bot/Dota2Bot/model/plugmanager.py", line 67, in add_plugin
    self.db.insert_info(plugin_name, status)
  File "/root/dota2bot/Dota2Bot/model/plugmanager.py", line 154, in insert_info
    self.c.execute(com)
sqlite3.OperationalError: no such column: True

**Comment by comradeXiong** [comment]
将154行的代码status改为 1 if status else 0
